### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by volter50000** [geeekpi/upsplus#101]
Battery Type.
The board has contacts for connecting an additional battery. I have a LiFePo4 battery. Is there enough voltage to operate the device? 2.7 - Critical voltage. 2.9 - minimum voltage 3.2 - normal voltage 3.7 - Maximum
Will the board work if all batteries are disconnected from it?

PS
It would be very good. If you would describe in detail the purpose of all registers. And also indicated which ones can be changed, and which ones are read-only. Maybe even examples. Because they raise a lot of questions.
For example, I needed to read the current/voltage/power values ​​from the INA219, but I found their addresses on the bus myself (upsplus.py file). There was no information anywhere on how to read data from the INA219.
Also interesting are the resistance values ​​of the current shunts.
You made an excellent device, it remains to make detailed documentation for it =))
Thanks !

**Comment by Weissnix4711** [comment]
I am also looking for a solution which supports either LTO or LFP cells. Anyone know if this is possible with this device?
