### ISSUE TITLE
Reset to factory defaults?

### ISSUE THREAD

**Issue by ArjenR49** [geeekpi/upsplus#105]
My UPS+ has had f/w version 10 for a long time now.

I would like to do a reset to factory defaults.
I remember from before version 10 it used to be possible by setting register 0x1B (=27) to 1, shutting down the PI, and then probably taking the batteries out and back again ... In fact documentation by geeekpi still supports this notion.

The simplest way to set register 0x1B and then check if it succeeded, is this:

pi@RPI-HUB:~ $ i2cset -y 1 0x17 27 1
pi@RPI-HUB:~ $ i2cget -y 1 0x17 27
0x00

or, less confusing:
pi@RPI-HUB:~ $ i2cset -y 1 0x17 0x1B 1
pi@RPI-HUB:~ $ i2cget -y 1 0x17 0x1B
0x00

As can be seen, the register doesn't get set.
I've tried the same with a python program, but results were equally poor.

So, how to enable a reset to factory defaults on version 10?

Edit:
Something apparently got reset, without taking batteries out or rebooting.
Before attempting to set 0x1B to 1 my reporting script reported (note register addresses at the end of the line):
...
Batteries fully discharged at (UPS/learned value):   3,400 V   (0x0F-0x10)
...
Now it reports:
...
Batteries fully discharged at (UPS/learned value):   4,100 V   (0x0F-0x10)
...

Another value also changed:
It was:
Batteries fully charged at (UPS/learned value):      4,316 V   (0x0D-0x0E)
Now it is:
Batteries fully charged at (UPS/learned value):      4,247 V   (0x0D-0x0E)

These registers will settle to some particular value after a discharging and charging cycle. Later on they will remain at those levels, except perhaps after a new battery discharging-charging cycle.
It seems that upon writing 1 to 0x1B for reset to defaults, those two settings are set to a little above and a little below current battery voltage.
Perhaps this is all the 'factory reset' will do, doing it without taking out batteries.
There could be more settings that get changed to defaults. Maybe I notice other changes later on.

Edit more:
Battery sampling interval also gets reset to 2 minutes, by writing 1 to the reset register 0x1B.

**Comment by yoyojacky** [comment]
please update the V14, it has been released for a while .
