### ISSUE TITLE
Restart not happen if power resume during shutdown countdown

### ISSUE THREAD

**Issue by isjfk** [geeekpi/upsplus#108]
If the power resume during shutdown countdown, the UPS should power off few seconds the power on again on timeout to restart the OS. This is a feature that known to work in firmware V7. However in latest V10 this scenario is no longer working.

Please refer to previous discussions here: #7 #15 

How to reproduce:

1. Upgrade firmware to latest V10
2. Disconnect charger
3. Execute: i2cset -y 1 0x17 0x18 30
4. Execute: sudo shutdown now
5. Connect charger before UPS power off
6. The UPS never power off
7. Unconnect charger again, the UPS continue 30 seconds countdown then power off

Looks like the countdown just stoped if charger is connected.

Expected behavior is in previous step 6, the UPS should power off few seconds, then power on again.
Flash to firmware V7 do bring this feature back.

**Comment by yoyojacky** [comment]
Recently, the V14 is released. you can update the firmware from OTA
