### ISSUE TITLE
Error 121 with no 17 registered

### ISSUE THREAD

**Issue by MarkStayt** [geeekpi/upsplus#109]
I am having issues installing my ups.  I run the sudo ./install.sh script and I get the folowing error

![image](https://user-images.githubusercontent.com/111309958/184700536-21346bcb-104a-4366-8a70-353884451b22.png)

When I run the sudo i2cdetect -y 1, I see 40, 45, 68 but no 17..

![image](https://user-images.githubusercontent.com/111309958/184700733-2db4b2d1-2bda-49b9-af14-e3717eaf3a14.png)

I have reseated the two cards twice and confirmed the contacts are good.  Any idea what I can do? 

Purchased on Amazon from GeeekPi Store as part of  ZP-0129 on Aug 9 and received it on the 13th.

**Comment by Pegi68** [comment]
I also had purcased two GeeekPi Raspberry Pi UPS from Amazon and had problems to install the second one.
The installation show me "The installation is incompatible" and failed.
If I checked the I2C Address with the i2c-tools and saw the first UPS was address 0x17 and the second had 0x18 !?
I corrected the upsplus.py script and can run it without problems.

Perhaps I could help al little bit.

**Comment by HS-Tech-kr** [comment]
I got same problem. There was [Errno121] and no 0x17 after I changed with new batteries.

**Comment by yoyojacky** [comment]
It seems like you are entering `OTA mode`, did you push the button while insert the batteries ?

**Comment by yoyojacky** [comment]
> I got same problem. There was [Errno121] and no 0x17 after I changed with new batteries. (with the brunt smell from the PCB)

Could you please take a photo on PCB near by the burnt position and send it back to me ?
