### ISSUE TITLE
Can UPS Plus EP-0136 use "Protected" 18650 Batteries?

### ISSUE THREAD

**Issue by pombears** [geeekpi/upsplus#113]
This is not an issue, but a general question on the UPS Plus EP-0136.
Can the device use "protected" 18650 batteries? They tend to be slightly larger than the standard ones: 70mm length (instead of 65mm for standard) and 18.9mm diameter (instead of 18mm).

**Comment by ArjenR49** [comment]
I don't think so.

There are other UPS's on the market which stipulate you should use 
protected batteries, but the battery holder won't allow for the extra 
length. I even doubt battery holders exist that could hold a protected 
cell, but prove me wrong ...

Op 12-11-2022 om 20:45 schreef pombears:

**Comment by pombears** [comment]
Thank you ArjenR49.
