### ISSUE TITLE
UPS Power up PI issue

### ISSUE THREAD

**Issue by Jiksaw0221** [geeekpi/upsplus#114]
Hi, is there any method to control ups power up PI only when the battery charging level is above protection voltage/ empty voltage?

**Comment by budiroots** [comment]
same issue with me :(
https://github.com/geeekpi/upsplus/issues/115

**Comment by yoyojacky** [comment]
Hi Jiksaw0221, 
It can not to control UPS Power up Pi due to the chipset on board is like a power bank, it will up once the UPS is power up.
