### ISSUE TITLE
Pi Supply voltage cannot be read. Always 0

### ISSUE THREAD

**Issue by Dulus0** [geeekpi/upsplus#12]
Input charger volatge and other charactersistics cannot be read. Second UPS that came.

Tried with RPi B+ & ZeroW with latest Raspian fully patched.
UPS updated to latest firmware.

Charger is connected, with good voltage and charging batteries.

Using code below:

import os
import time
import logging
from ina219 import INA219,DeviceRangeError

ina = INA219(0.00725, address=0x40)
ina.configure()
while True:
    print("Raspberry Pi Supply Voltage: %.3f V" % ina.voltage())
    print("Raspberry Pi Current Current Consumption: %.3f mA" % ina.current())
    print("Raspberry Pi Current Power Consumption: %.3f mW" % ina.power())
    print("Shunt voltage: %.3f mV" % ina.shunt_voltage())
    time.sleep(1)
    
    
 It only shows 0 values:
 
 Raspberry Pi Supply Voltage: 0.000 V
Raspberry Pi Current Current Consumption: 0.000 mA
Raspberry Pi Current Power Consumption: 0.000 mW
Shunt voltage: 0.000 mV
Raspberry Pi Supply Voltage: 0.000 V
Raspberry Pi Current Current Consumption: 0.000 mA
Raspberry Pi Current Power Consumption: 0.000 mW
Shunt voltage: 0.000 mV
Raspberry Pi Supply Voltage: 0.000 V
Raspberry Pi Current Current Consumption: 0.000 mA
Raspberry Pi Current Power Consumption: 0.000 mW
Shunt voltage: 0.000 mV
Raspberry Pi Supply Voltage: 0.000 V
Raspberry Pi Current Current Consumption: 0.000 mA
Raspberry Pi Current Power Consumption: 0.000 mW
Shunt voltage: 0.000 mV

**Comment by nickfox-taterli** [comment]
You can upgrade the firmware and try again, or contact the aftermarket and provide the serial number for inspection.

Please also provide a photo of the front of the product, connected to the Raspberry Pi and a separate picture to check if it is a faulty product.
