### ISSUE TITLE
AC Power 4Amp Geekworm

### ISSUE THREAD

**Issue by hellresistor** [geeekpi/upsplus#120]
The UPS support this power source?

https://geekworm.com/collections/raspberry-pi/products/20w-5v-4a-type-c-psu

designed for RPI4. Best Regards

**Comment by hellresistor** [comment]
well.. in ups board its written 10W/2A max .. :|

**Comment by yoyojacky** [comment]
yes, it will support this power supply, and you can use it as charging device.
