### ISSUE TITLE
Not charging

### ISSUE THREAD

**Issue by soumyajit02** [geeekpi/upsplus#126]
Only the first Blue led is blinking after charging for a whole night battery voltage is 3.69V and not going up. The pi is not starting with the ups power alone. It was working fine previously but after reinstalling the ups module it's giving me this problem. charger: xiaomi 2A charger

**Comment by soumyajit02** [comment]
I checked the output voltage of the ups module when connected to the rpi its around 2.5V its supposed to be around 5v I don't know thy 2.5V

**Comment by yoyojacky** [comment]
please change a power supply which can offer 5V/ 3A ,  the raspberry pi's power consumption is faster than charging speed, so it may drain out your batteries, and you may need to change a new batteries and try again.
