### ISSUE TITLE
Batteries not detected - brand new - troubleshooting assistance requested

### ISSUE THREAD

**Issue by ShamimIslam** [geeekpi/upsplus#129]
Hello.

I purchased the GeekPi case w/ the UPS hat bundled on a PI 4 B.

I purchased Panasonic flat top 18650 high drain unprotected batteries. https://www.batteryjunction.com/panasonic-ncr18650b-3400.html

When I plug in the charging cable, the PI starts up. When I unplug the charging cable, the PI turns off immediately.

What I see is below. This doesn't seem right as the batteries are 3.7V and I have them both pointing in the same direction along the lines of the polarity listed on the UPS.

Can you please help me understand what steps to take to resolve this problem or what I might have done incorrectly?

Thanks.

P.S. I had to turn off the shutdown because it tries to shut down automatically.

------------------------------------------------------------
------Current information of the detected Raspberry Pi------
------------------------------------------------------------
Raspberry Pi Supply Voltage: 5.288 V
Raspberry Pi Current Current Consumption: 773.759 mA
Raspberry Pi Current Power Consumption: 3909.167 mW
------------------------------------------------------------
-------------------Batteries information-------------------
------------------------------------------------------------
Voltage of Batteries: 3.480 V
Battery Current (discharge) Rate: -36.098 mA
Current Battery Power Consumption: 126.829 mW
------------------------------------------------------------
Successfully set the protection voltage to: 4 mV
------------------------------------------------------------
Currently not charging.

**Comment by yoyojacky** [comment]
Please fully charged your Batteries and try again, and at the same time, please make sure protection voltage is setting to 3.7V but not 4mV, it will drain out the batteris and damage the batteries, it seems like the charging speed can not catch up with the power comsumption speed .... please change batteries and change power supply and try again.
