### ISSUE TITLE
charging interface status not correctly reported

### ISSUE THREAD

**Issue by frtz13** [geeekpi/upsplus#13]
today I ran into the following problem: reading i2c bus about the current charging interface status does not work.
Problems in this situation:
Full-featured-demo-code.py reported 5151mV on Type-C USB, regardless of Type-C USB being connected to charger or not.
Full-featured-demo-code.py reported 9mV on Micro-USB,  connected to a charger or not.
in this situation, battery charge and discharge worked normally and could be observed via the INA sensors and the LEDs.
once Rasberry-Pi was shut down and the power supply disconnected: the switch did not shut off the UPS.
Taking out the batteries and putting them back in restored normal operation.

Full-featured-demo-code.py result with both micro-USB and Type-C-USB disconnected:

pi@rpi-home-ass:~/upsplus $ python3 Full-featured-demo-code.py
Raspberry Pi power supply voltage: 4.880 V
Current current consumption of Raspberry Pi: 1933.726 mA
Current power consumption of Raspberry Pi: 8787.216 mW
Batteries Voltage: 4.092 V
Battery current (discharge), rate: 2697.805 mA
Current battery power consumption: 11980.488 mW
Current processor voltage: 3290 mV
Current Raspberry Pi report voltage: 4947 mV
Current battery port report voltage: 4171 mV
Current charging interface report voltage (Type C): 5151 mV
Current charging interface report voltage (Micro USB): 9 mV
Currently charging through Type C.
Current battery temperature (estimated): 41 degC
Full battery voltage: 4285 mV
Battery empty voltage: 3700 mV
Battery protection voltage: 3700 mV
Battery remaining capacity: 99 %
Sampling period: 2 Min
Current power state: normal
No shutdown countdown!
Automatically turn on when there is external power supply!
No restart countdown!
Accumulated running time: 813992 sec
Accumulated charged time: 817347 sec
This running time: 323490 sec
Version number: 4
Serial Number is:(…)

**Comment by nickfox-taterli** [comment]
You can upgrade the firmware and try again, or contact the aftermarket and provide the serial number for inspection.
