### ISSUE TITLE
I2c read errors

### ISSUE THREAD

**Issue by UnscrewLater** [geeekpi/upsplus#136]
I have been seeing random I2c read errors using Python, C++ and i2c-tools. It's very easy to demonstrate using this shell command:
`(T=$(date +%s); while V=$(i2cget -y 1 0x17 17 w); do\
 [ $(( $V )) -eq 3700 ] || break; echo -n . ; LOOPS=$(( $LOOPS + 1));\
 done; echo "$(( $(date +%s) - $T )) secs, LOOP $LOOPS, PROTECT=$V")`
i2cget returns an error every few minutes and the value read is incorrect about 1 in 5000 reads. I2c bus #1 has the UpsPlus and an LCD display (not in use).
The board is a RPi2b running 'Raspbian GNU/Linux 11 (bullseye)'.
Any ideas?

**Comment by yoyojacky** [comment]
Could you please execute this command and send me the feedback ? 
```bash
i2cdetect -y 1 
```
