### ISSUE TITLE
EP-0118 does not respond via i2c

### ISSUE THREAD

**Issue by bazsi** [geeekpi/upsplus#139]
I have bought an EPS-0118 a while back (like 3 years ago) and I started using it now. 

It did not respond via i2c at first, and then I noticed that the pogo pins connecting the i2c connectors on the Pi were not connected. I have now soldered connections, but it still does not respond to any i2c packets. I have a scope and looked at the actual i2c messages and my Pi does send out the frames but then no response.

I started wondering if I needed a firmware upgrade, but how to upgrade if i2c is not working? Any guidance would be appreciated.

**Comment by yoyojacky** [comment]
Could you please refer to this URL: [wiki.52pi.com/index.php?https://wiki.52pi.com/index.php?title=EP-0136](https://wiki.52pi.com/index.php?title=EP-0136) ? and follow the instructions to upgrade firmware via OTA.
