### ISSUE TITLE
Bookworm Or RPi 5 Support?

### ISSUE THREAD

**Issue by RyukenKai** [geeekpi/upsplus#141]
Not sure if I'm doing this correctly but wondering if there is a plan to support RPi OS Bookworm or RPi 5 in the future.  I know a lot has changed with the latest updates and RPi 5 Upgrade so it may not be possible with the current code.

**Comment by yoyojacky** [comment]
Hi RyukenKai, It can not fit for Raspberry Pi 5 due to the power may not suffisient for Raspberry  Pi 5, it may cause undervoltage warning...
