### ISSUE TITLE
Firmware v14, changelog/release notes, it's not possible to revert to older version after update to v14

### ISSUE THREAD

**Issue by jens-roth** [geeekpi/upsplus#143]
Hello. I'm using two different UPS Plus EP-1036 (rev. 5.4 2020-01-05 PCB03a) and (rev. 5.0 2020/12/23 PCB01b) both on Firmware v14. Because I can not revert to Firmware v10. OTA_firmware_upgrade.py failed to download any other Firmware version ("File not found").
Is there a changelog or some release notes available?
I tried the OTA_firmware_upgrade.py Scipt, which allows me to update both UPS-Plus to the latest Firmware v14. It's not possible to download any older Versions ("File not found").
I've downloaded a file from this forum with v10, but I'm concerned to use it to flash v10.
Is a solution/script available to select the firmware version to download/flash it? Thanks a lot!

**Comment by yoyojacky** [comment]
Hi jens-roth， 
Older versions do not support rollback; it is recommended to use the latest version, which is compatible with all hardware and can be used with confidence.
