### ISSUE TITLE
Question about the OTA Firmware Update NOTE.

### ISSUE THREAD

**Issue by hellresistor** [geeekpi/upsplus#20]
"*** NOTE: Do not assemble UPS with Raspberry Pi with Batteries in it ***"

This is the 'Inverse' method of 1st assembly on rpi (https://wiki.52pi.com/index.php/UPS_Plus_SKU:_EP-0136#How_To_Assemble ), Right?

**Comment by yoyojacky** [comment]
The icon on the wiki is to show the relationship between their structures, not the order of installation, we will arrange to retake the picture, thank you for your tips
