### ISSUE TITLE
Charging port voltage incorrectly reported

### ISSUE THREAD

**Issue by frtz13** [geeekpi/upsplus#28]
using firmware version 7
my UPS board has gone into a state where it no longer reports the voltage on the USB charging ports.
the reported USB-C charging port voltage stays at 4865mV regardless of a power supply connected or not.
the reported Micro-USB charging port stays at 0mV regardless of a power supply connected or not.
all other UPS functions seem normal: output power, battery charging, other measurements, LEDs.
nothing special has happened to the UPS, it was just doing its job.

NB: this charging port reporting error now has happened for the second time. it already happened a couple of days ago with firmware version 4. I did not report it at that time because I did a firmware upgrade shortly afterwards. In this situation, the only way to establish normal operation again was to take out the batteries. it was impossible to switch off the UPS using the button. To reset the UPS I had to take out the batteries with the UPS running.

Edit May 17th 7:45 UT: I keep the UPS in the "non reporting state". please tell me of any other useful information for you.

Edit May 18th 9:15 UT: I realized that also battery temperature is no longer updated, it is reported as being 44°C, with no fluctuations at all, which is not normal. As I keep battery temperature history, I found out that the UPS went into this buggy state on May 15th, 19:16 UT. My UPS reports back telemetry data to https://api.thekoziolfoundation.com. I can send you the UID of my UPS in a private message if you are interested.  

$ python3 Full-featured-demo-code.py
Raspberry Pi power supply voltage: 4.888 V
Current current consumption of Raspberry Pi: 1648.276 mA
Current power consumption of Raspberry Pi: 7966.358 mW
Batteries Voltage: 4.148 V
Battery current (discharge), rate: 2120.000 mA
Current battery power consumption: 8775.610 mW
Current processor voltage: 3281 mV
Current Raspberry Pi report voltage: 4927 mV
Current battery port report voltage: 4190 mV
Current charging interface report voltage (Type C): 4865 mV
Current charging interface report voltage (Micro USB): 0 mV
Currently charging through Type C.
Current battery temperature (estimated): 44 degC
Full battery voltage: 4287 mV
Battery empty voltage: 3700 mV
Battery protection voltage: 3700 mV
Battery remaining capacity: 98 %
Sampling period: 2 Min
Current power state: normal
No shutdown countdown!
Automatically turn on when there is external power supply!
No restart countdown!
Accumulated running time: 273684 sec
Accumulated charged time: 285221 sec
This running time: 5149 sec
Version number: 7
Serial Number is:(...)

**Comment by nickfox-taterli** [comment]
The firmware sometimes freezes and accumulated running timer no longer run as this is a random error(unusual and random) so we have had a bit of trouble fixing it,but are working on it.

Workarounds:

Reads the battery current sampled by the INA219. If the battery is continuously discharged, it is assumed that the external power supply has been removed or that charging is not possible.
