### ISSUE TITLE
Disconnect power from the 2 USB A ports and the USB type C port?

### ISSUE THREAD

**Issue by ArjenR49** [geeekpi/upsplus#29]
When the UPS cuts power to the Pi, it leaves the USB ports powered.
If the hardware allows it, it might be useful to optionally have the UPS cut that power, too.

**Comment by nickfox-taterli** [comment]
This requires a hardware modification, as this is a DCDC topology, it may not go to 0V even when switched off, we will discuss this with the hardware design.

**Comment by ArjenR49** [comment]
Thanks
