### ISSUE TITLE
UPS is always shutting down when disconnected from PS

### ISSUE THREAD

**Issue by deHarro** [geeekpi/upsplus#3]
In "upsplus.py" on line 86 you compare ina.voltage() to PROTECT_VOLT.

The return value of ina.voltage() is something like "4.208".
PROTECT_VOLT is 3700.

Therefore the comparison 
`    if ina.voltage() < (PROTECT_VOLT + 200):`
will always be true and the Raspberry is always shut down when the power supply is diconnected.

Remedy:
`    if ((ina.voltage() * 1000) < (PROTECT_VOLT + 200)):`

Harry

**Comment by nickfox-taterli** [comment]
Thank you for the patch.
