### ISSUE TITLE
The latest f/w version?

### ISSUE THREAD

**Issue by ArjenR49** [geeekpi/upsplus#32]
Trying to upgrade the f/w involves taking out 4 screws and battery manipulation.
Doing that just to see, IF there is a newer version than the one I have, is a waste of effort, although the upgrade procedure itself works just fine.

Is there a way for UPS Plus users to see what the latest f/w version is?

My UPS is on version 7 now.

**Comment by hellresistor** [comment]
> Is there a way for UPS Plus users to see what the latest f/w version is?

+1
