### ISSUE TITLE
[Info] background script for automatic shutdown and publishing UPS status to MQTT broker

### ISSUE THREAD

**Issue by frtz13** [geeekpi/upsplus#35]
not an issue, just information... if anyone is interested... I put together a python script running in the background managing automatic shutdown and publishing some UPS status data (battery temperature, on battery status, charging/discharging current, output current, and more) to an MQTT broker. for more info, see: https://github.com/frtz13/UPSPlus_mqtt

**Comment by hellresistor** [comment]
friend! I get this UPS with goal to work on Rpi with homeassistant. This is 💯 🥇
