### ISSUE TITLE
UPS stops powering the system with charger still attached

### ISSUE THREAD

**Issue by deHarro** [geeekpi/upsplus#36]
I have a Raspberry 3 B+ with the UPSplus running firmware V4.
From time to time the UPS stops supplying the system (UPS + RPi) and the RPi is powered from the batteries from this moment on.

From here on there arise several problems.

**The first problem**: In the script "upsPlus.py" the case "check the battery voltage" is not reached, since the charger is still attached and delivers a voltage which is recognized. -> Remedy: Move the case one level out. This part of the script should read as 
```
if (aReceiveBuf[8] << 8 | aReceiveBuf[7]) > 4000:
    print('-'*60)
    print('Currently charging via Type C Port.')
elif (aReceiveBuf[10] << 8 | aReceiveBuf[9])> 4000:
    print('-'*60)
    print('Currently charging via Micro USB Port.')
else:
    print('-'*60)
    print('Currently not charging.')

# Consider shutting down to save data or send notifications
if (ina.voltage() * 1000) < (PROTECT_VOLT + 200):                 # <<-- this case was situated in the else clause
    print('-'*60)
    print('The battery is going to dead! Ready to shut down!')
# It will cut off power when initialized shutdown sequence.
    bus.write_byte_data(DEVICE_ADDR, 24,240)
    os.system("sudo sync && sudo halt")
    while True:
        time.sleep(10)
```

**The second problem**: The RPi is never restarted.
**The most significant problem**: WHY AT ALL does the UPS stop feeding the current from the charger to the system?

I am in contact with the hotline staff for some days now on this problem and they are eager to pass information from me and the development crew to and fro, but all in all I am not satisfied with this slow communication.
To speed up the conversation, I now raise this issue.

Harry

**Comment by nickfox-taterli** [comment]
1)There is nothing wrong with this script, when charging it will absorb power from the charger at the same time, unless your battery is unable to meet the charging requirements, e.g. capacity is too low, load is too high, when discharging it then check if it is over discharged, if you need to implement your own function please modify your own script to use it, this does not require you to use our reference script.

2)The second problem is that you need to set it to reboot when AC comes in before it will reboot, please read the wiki documentation provided carefully.

**Comment by deHarro** [comment]
1) You are right, as long as the attached charger is correctly recognized by the UPS.

In my case the UPS cuts power from the charger to the system and switches to battery operation after several hours.
In this situation the provided script checks for power on the USB ports, see a voltage > 4 V and therefore does not check for the battery voltage.

This is an error case, I know, but my changes do no harm to the normal operation of the script.

2) I read the docu many times for sure :) In other issues I read, that there were changes to the firmware and the wiki, so I should reread the docu.
Is there a way of being informed on changes of the docu and the frimware?
Thanks!

Harry
Harry

**Comment by deHarro** [comment]
Concerning the third problem...
Is the UPS firmware checking the power levels of the different circuits?
If so, and the readings from the INA chip is wya too high, does the firmware shut down the charger power path?

**Comment by deHarro** [comment]
Hi @nickfox-taterli,
I think to and fro concerning this unintended interruption of the charger power path.

My ideas about possibilities producing this situation are as follows:
Perhaps my charger has (short) drop outs.
The UPS realizes those drop outs and thinks "charger is off", resulting in switching to batteries.

If this imagination is true, I would try to filter out such short drop outs by sampling several times to be sure, that the charger is actually dead.
Additionally I would expect, that the UPS permanently checks for "reactivation" of the charger and then switches back to charger powered operation.

In the error case, arising at mine and @hellresistors (see [here](https://github.com/geeekpi/upsplus/pull/38#issuecomment-845363217)) UPS, this recognition of "charger is ready" is omitted, as shown in my trace files.

Harry

**Comment by hellresistor** [comment]
I have get this issue today again :( 
My solution. detach ups from rpi. put batteries on ups and connect power cable until 4leds fix.

**Comment by deHarro** [comment]
Hi hellresistor,
that's not really a **solution**, maybe a workaround.
The solution would be, that the UPS firmware prevents the deep discharge under any condition. I hope the developers are on that now.

But you are right. 
The error case yields to a completely depleted battery (around 2.5 V in my case, what is dangerously low for a LiPo cell, i must say). 
To get the RPi running again one has to disconnect the RPi from the UPS. 

This is because the UPS tries to "trickle charge" the depleted cell with a very low current to get it into sane conditions (that is cell voltage greater than 3.6 V), before it applies the normal or even fast charge current.
And this low trickle charge current prevents the RPi from starting.
The RPi draws too much current when starting, so the battery doesn't get charged to the point where the UPS would apply enough current for both, charging the battery and driving the RPi -> deadlock.
The only way out is detaching the RPi as you said.

Harry

**Comment by hellresistor** [comment]
less than 48h. off again :/

**Comment by deHarro** [comment]
Hi @hellresistor,

I am in touch with GeeekPi after-sales staff. They told me to send back my two UPS to check, what the problem might be. The decvices are on the way to china now. I have to wait for a solution.

Harry

**Comment by nickfox-taterli** [comment]
The charging process is like this:

1) Check if the external adapter is present, if sampling, restart charging every [sampling cycle].
2) If the external adapter is present, you will see that all the power indicator LEDs will go off and then come back on every [sample cycle].
3) If the external adapter exists, it will continue to charge, but in fact, because the discharge is also continuous, at least part of the user will maintain the battery charge state, and the other part will be used directly for load power.
4) If the presence of the adapter is observed, and the battery continues to discharge, it means that the charging rate is not as fast as the discharge rate.
5) If you observe phenomenon 4, remove the load (such as Raspberry Pi) can fill the battery, and you can observe phenomenon 2, it means that the battery or adapter needs to be replaced.
6) If you need to update the adapter, QC fast charging adapter will be better.
7) We have arranged for the return of the product for testing, the test results will have A release.

Translated with www.DeepL.com/Translator (free version)

**Comment by deHarro** [comment]
Hello @nickfox-taterli
What you describe is the straight forward case. This is, what your hardware and firmware is supposed to do.
But we talk about an erroneous situation and have to track down the reason, right?
I try to support you as hard I could, but I just have the impression, that you are not interested in my arguing and evidence and cling to your own opinion. 
Maybe we have problems to understand each other since we both are not native-speakers in English.
So I give it another try to explain the problem as I see it…

As of 4.
As presented before (have a look at the [trace file ](https://github.com/geeekpi/upsplus/pull/38#issuecomment-845724575) I provided you with), there is no "...and the battery continues to discharge...". 
-> Please copy the trace and show it fully in an editor capable of displaying 100 columns or more to see the comments.
-> The system runs perfectly for many hours from the charger. In this time the battery is **charged** AND the RPi is powered without any problems, all that in parallel. This leads to the fact: The charger is perfectly able to charge the batteries and drive the RPi all the time.
-> Then, suddenly, the UPS switched something and the power of the charger is no longer routed to the system. From here on, the RPI is powered only from batteries and the charger sits there, doing nothing.

Explicitly: I postulate a problem in the firmware of the STM32 or in the collaboration of STM32 and IP5328.

I am able, and did that in the past, to provide you with evidence, that all devices in my test setup are working as expected, except the UPS.

The situation as demonstrated by me:
1. The charger is able to deliver the needed power for driving the RPi and charging the batteries all the time.
2. The system, consisting of UPS, RPi and batteries, is running without problems for many hours (mostly more than 1 day, 24 hours).
3. The batteries are full, either charged beforehand in an external charger or charged by the UPS. Both is tested and runs without problems.
4. Temperatures are sane, the batteries are cold (room temperature). The RPi and the UPS are warm but not hot. All temperatures are in a steady state since hours.
The fourth blue LED is blinking permanently, the batteries are never reaching 100% state of charge.
5. (**5.**) Without changing anything in this "OK" situation, the UPS suddenly stops charging the batteries and stops powering the RPi. 
The four LEDs are going ON steadily (blinking of the fourth LED stops).

Additional information I:
In state 5. the four blue LEDs are permanently showing FULL state (all ON, not blinking).
Then, after around 3.5 to 4 hours, the batteries are depleted to 2.5 V at that time and the charger is still operating flawlessly, delivers 5.1 V to the UPS.
And the four blue LEDs are still showing FULL state.

Additional information II:
This identical misbehavior is observed with a standard Raspberry 4 charger, rated 3A @ 5.1 V, and with a Fast charger from Google phone, rated 2A @ 9V. This second charger negotiates fast charge mode with the UPS, it charges at 9V.
I tested another charger, rated 3A @ 5.0 V, this one is NOT able to power the system. I do not use this one, accordingly.

As reason for this (**5.**) reaction of the UPS I can imagine:
1. The charger may have a short drop out (only as hypothesis to work with), the voltage falls below a threshold and the UPS (IP5328 or STM32) decides, that there is no charger attached any more.
2. ?

If the firmware of the STM32 is the culprit:
1. To prevent falling into this situation you may sample the voltages at the charger ports several times to filter out glitches/drop outs of the voltages.
If you already do this and the error happens anyway:
2. To come out of the described situation you may check the status of the charger ports even in the branch where the STM32 might be after having recognized a drop out of the charger voltages.

2. is significant, because in the error state this checking obviously seems to be omitted.
Why?
-> When 5. occurs, the UPS has the information, that there is a charger attached, One can see this by reading registers 0x07-0x08 and 0x09-0x0A. I do that in my script and the voltage at the charger port is always present.
And despite this fact, the charger is nevertheless NOT powering the system, the system is powered from the batteries.

If the IP5328 is the culprit:
No Idea, sorry :(

Harry

**Comment by iutipikin** [comment]
@deHarro @yoyojacky

Hi folks, 

surprisingly I have exact same issue with EP-0118 (non-plus, upgraded UPS version). I have observed exactly same behavior as described by @deHarro in https://github.com/geeekpi/upsplus/issues/36#issuecomment-850311607:

Batteries are: 3C 7.8A, 3.7V INR18650-26E
So scenario is:
- I attach power supply (tried 61W/20W both with PD, same thing) via usb-c -> micro usb 3A cable
- while status LEDs are blinking everything is ok, it can last for 24-48 hours
- then something happened (I cannot trace what, as EP-0118 have useless ina219 module)
- now LEDs are not blinking, constant 4 LEDs + RPi power status, but RPi is actually on battery
- then batteries are drained, RPi will go offline while LEDs still show full charge (4 LEDs constantly on)

Then I start RPi via button again, status LEDs will blink ones and from now on will show real battery status - charging, starting from one LED.  

That I also did: I charged batteries while RPi is offline until 4 constant LEDs, attach cable to RPi directly and after its start press the button - I suppose what now RPi should be powered via its on usb-c port, but UPS was discharging. 

I don't know if its a firmware of hardware issue, but my device probably is not fixable, as it is not support firmware update.

**Comment by hellresistor** [comment]
guys.. someone can test with microUSB insteade USB-C ? (paranoic quastion)

**Comment by iutipikin** [comment]
@hellresistor charging (modes, voltages, etc) is a responsibility of target device controller, not charger itself. So such swap (usb-c charger to classic one) will not do the trick. 

A big disappointment for me is what model EP-0136 by your reports has the same issue as mine EP-0118, as I thought to buy this new unit. Now I'm stuck, as I still need UPS for my Home Assistant solution and models from GeekPi can have such an major issue.

**Comment by deHarro** [comment]
@iutipikin, @hellresistor 

At the moment I'm pretty convinced, that @nickfox-taterli and @yoyojacky are striving hard to find and fix the problem.
I sent my two UPS back to GeeekPi to let them have a look at the devices. 
In conjunction with my descriptions and trace files they should easily be able to track down the problem.

Harry

**Comment by iutipikin** [comment]
@deHarro @nickfox-taterli 
Any updates regarding this topic?

**Comment by deHarro** [comment]
@iutipikin 
Hi Iurii, 
nothing new from my side.
That will be the fact until GeeekPi provide me with a new UPS. Currently I have no UPS here, so I'm sitting, chewing nails...
Harry

**Comment by ArjenR49** [comment]
My UPS worked  OK on f/w v.7, but version 8 has a nasty bug. Waiting for 
a newer version, that actually can handle writes to i2c memory ... I'd 
take version 7 back for the time being ...

Op 06-06-2021 om 12:46 schreef deHarro:

**Comment by leandroalbero** [comment]
I have the exact same problem. Charger negotiates fast charge at 9V and initially charges at around 2 amps, but after 24-48 hours the fourth LED stops blinking and stays on (batteries never get fully charged and I can't change full voltage register), after a few hours with all leds static, the batteries get dangerously discharged and raspberry pi stops working. 
I got this upsplus.py output that says "Currently charging via Type C port" and "Battery Current (**discharge**) Rate: 3575.854 mA": 
```
admin@exodus:~ $ python3 upsplus/upsplus.py 
------------------------------------------------------------
------Current information of the detected Raspberry Pi------
------------------------------------------------------------
Raspberry Pi Supply Voltage: 4.920 V
Raspberry Pi Current Current Consumption: 2812.279 mA
Raspberry Pi Current Power Consumption: 13436.501 mW
------------------------------------------------------------
-------------------Batteries information-------------------
------------------------------------------------------------
Voltage of Batteries: 4.088 V
Battery Current (discharge) Rate: 3575.854 mA
Current Battery Power Consumption: 14795.122 mW
------------------------------------------------------------
Successfully set the protection voltage to: 3500 mV
UID:00xxxxxxx/42xxxxxx/xxxxxx36
------------------------------------------------------------
Currently charging via Type C Port.
admin@exodus:~ $ 
```
I am using brand new NCR18650 and an Apple 20W USB-C charger. I've also tried a DJI charger with QC3.0 rated at 18W. Raspberry Pi 4 8GB with a 2.5" mechanical hard drive. UPS plus ver. 8

**Comment by nickfox-taterli** [comment]
> I have the exact same problem. Charger negotiates fast charge at 9V and initially charges at around 2 amps, but after 24-48 hours the fourth LED stops blinking and stays on (batteries never get fully charged and [I can't change full voltage register](https://github.com/geeekpi/upsplus/issues/16#issuecomment-852184252)), after a few hours with all leds static, the batteries get dangerously discharged and raspberry pi stops working.
> I got this upsplus.py output that says "Currently charging via Type C port" and "Battery Current (**discharge**) Rate: 3575.854 mA":
> 
> ```
> admin@exodus:~ $ python3 upsplus/upsplus.py 
> ------------------------------------------------------------
> ------Current information of the detected Raspberry Pi------
> ------------------------------------------------------------
> Raspberry Pi Supply Voltage: 4.920 V
> Raspberry Pi Current Current Consumption: 2812.279 mA
> Raspberry Pi Current Power Consumption: 13436.501 mW
> ------------------------------------------------------------
> -------------------Batteries information-------------------
> ------------------------------------------------------------
> Voltage of Batteries: 4.088 V
> Battery Current (discharge) Rate: 3575.854 mA
> Current Battery Power Consumption: 14795.122 mW
> ------------------------------------------------------------
> Successfully set the protection voltage to: 3500 mV
> UID:00xxxxxxx/42xxxxxx/xxxxxx36
> ------------------------------------------------------------
> Currently charging via Type C Port.
> admin@exodus:~ $ 
> ```
> 
> I am using brand new NCR18650 and an Apple 20W USB-C charger. I've also tried a DJI charger with QC3.0 rated at 18W. Raspberry Pi 4 8GB with a 2.5" mechanical hard drive. UPS plus ver. 8

We retrieved your usage records and found that your UPS has been working from five days ago until now, no shutdown phenomenon, the start time is 2021-06-04 12:44:28 (UTC), and the charging port is USB-C, the voltage is 5V, not 9V.

**Comment by leandroalbero** [comment]
> > I have the exact same problem. Charger negotiates fast charge at 9V and initially charges at around 2 amps, but after 24-48 hours the fourth LED stops blinking and stays on (batteries never get fully charged and [I can't change full voltage register](https://github.com/geeekpi/upsplus/issues/16#issuecomment-852184252)), after a few hours with all leds static, the batteries get dangerously discharged and raspberry pi stops working.
> 
> > I got this upsplus.py output that says "Currently charging via Type C port" and "Battery Current (**discharge**) Rate: 3575.854 mA":
> 
> > 
> 
> > ```
> 
> > admin@exodus:~ $ python3 upsplus/upsplus.py 
> 
> > ------------------------------------------------------------
> 
> > ------Current information of the detected Raspberry Pi------
> 
> > ------------------------------------------------------------
> 
> > Raspberry Pi Supply Voltage: 4.920 V
> 
> > Raspberry Pi Current Current Consumption: 2812.279 mA
> 
> > Raspberry Pi Current Power Consumption: 13436.501 mW
> 
> > ------------------------------------------------------------
> 
> > -------------------Batteries information-------------------
> 
> > ------------------------------------------------------------
> 
> > Voltage of Batteries: 4.088 V
> 
> > Battery Current (discharge) Rate: 3575.854 mA
> 
> > Current Battery Power Consumption: 14795.122 mW
> 
> > ------------------------------------------------------------
> 
> > Successfully set the protection voltage to: 3500 mV
> 
> > UID:00xxxxxxx/42xxxxxx/xxxxxx36
> 
> > ------------------------------------------------------------
> 
> > Currently charging via Type C Port.
> 
> > admin@exodus:~ $ 
> 
> > ```
> 
> > 
> 
> > I am using brand new NCR18650 and an Apple 20W USB-C charger. I've also tried a DJI charger with QC3.0 rated at 18W. Raspberry Pi 4 8GB with a 2.5" mechanical hard drive. UPS plus ver. 8
> 
> 
> 
> We retrieved your usage records and found that your UPS has been working from five days ago until now, no shutdown phenomenon, the start time is 2021-06-04 12:44:28 (UTC), and the charging port is USB-C, the voltage is 5V, not 9V.

Hello, thanks for replying but I am telling you it's 9V according to my Satechi Power meter and Fluke multimeter. Just yesterday I noticed that it was sitting at 9V 0.00A with all four leds on and battery draining quickly. I restarted the power supply before the batteries got too low on voltage. Also, why can't I change the full voltage register? Fourth LED is always blinking and I dont want the battery to stay at 4.25V for months ![image](https://user-images.githubusercontent.com/12993089/121486741-b52e7280-c9d1-11eb-957b-f4884a7601ff.jpeg)
Thank you again for your time

**Comment by leandroalbero** [comment]
Happened again: 
```
admin@exodus:~ $ python3 upsplus/upsplus.py 
------------------------------------------------------------
------Current information of the detected Raspberry Pi------
------------------------------------------------------------
Raspberry Pi Supply Voltage: 4.932 V
Raspberry Pi Current Current Consumption: 2310.345 mA
Raspberry Pi Current Power Consumption: 10957.107 mW
------------------------------------------------------------
-------------------Batteries information-------------------
------------------------------------------------------------
Voltage of Batteries: 4.064 V
Battery Current (discharge) Rate: 3060.000 mA
Current Battery Power Consumption: 12317.073 mW
------------------------------------------------------------
Successfully set the protection voltage to: 3500 mV
UID:00350009/42415711/20323236
------------------------------------------------------------
Currently charging via Type C Port.
admin@exodus:~ $ 
```

```
admin@exodus:~ $ i2cdump -y 1 0x17
No size specified (using byte-data access)
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
00: 01 03 0d 54 13 df 0f d0 23 00 00 31 00 b3 10 ac    ???T????#..1.???
10: 0e 74 0e 63 00 01 00 01 00 01 00 00 35 70 04 00    ?t?c.?.?.?..5p?.
20: 9b 70 04 00 28 4c 01 00 08 00 01 00 00 00 00 00    ?p?.(L?.?.?.....
```

```
admin@exodus:~ $ python3 upsplus/Full-featured-demo-code.py 
Raspberry Pi power supply voltage: 4.920 V
Current current consumption of Raspberry Pi: 2838.520 mA
Current power consumption of Raspberry Pi: 13571.068 mW
Batteries Voltage: 4.016 V
Battery current (discharge), rate: 4173.902 mA
Current battery power consumption: 18068.293 mW
Current processor voltage: 3331 mV
Current Raspberry Pi report voltage: 4940 mV
Current battery port report voltage: 4024 mV
Current charging interface report voltage (Type C): 9113 mV
Current charging interface report voltage (Micro USB): 0 mV
Currently charging through Type C.
Current battery temperature (estimated): 50 degC
Full battery voltage: 4275 mV
Battery empty voltage: 3756 mV
Battery protection voltage: 3712 mV
Battery remaining capacity: 99 %
Sampling period: 1 Min
Current power state: normal
No shutdown countdown!
Automatically turn on when there is external power supply!
No restart countdown!
Accumulated running time: 290938 sec
Accumulated charged time: 291040 sec
This running time: 85101 sec
Version number: 8 
```

![IMG_7317](https://user-images.githubusercontent.com/12993089/121587782-75997200-ca35-11eb-9904-4869b90adab7.jpg)

**Comment by leandroalbero** [comment]
I set up a telegram bot to warn me when batteries voltage starts dropping while connected to the charger and noticed it happens every 24 hours with quite a lot of certainty: 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/12993089/121872134-34d77c80-cd05-11eb-8f8b-e7d617bd98f2.png">
When the bot messages me, I plug and unplug the power supply in order to keep the raspberry pi from powering down after a few hours.

**Comment by deHarro** [comment]
This is the error I and some others encounter, too.
Up til now I have no reaction from GeeekPi side.
Last statement concerning this was from @nickfox-taterli, telling they assigned some tests to a person (besides @yoyojacky) to proof the error.
No public results, yet.

Good idea to let you be informed from the RPi.
Go one step beyond and use one of the RPis GPIOs to interrupt the power supply automatically...
Weird but constructive :)

Harry

**Comment by yoyojacky** [comment]
Sorry for my slow response,  and I have already tested two USP PLUS which sent back from Harry,  and  One of the pins of the UPS charging chip was unsoldered. After re-soldering, the firmware of V8 was upgraded. After running for a week, there was no power failure. Other one works properly .
and I used a charger which supports QC protocol, and charging voltage is 9.01V

**Comment by yoyojacky** [comment]
> This is the error I and some others encounter, too.
> Up til now I have no reaction from GeeekPi side.
> Last statement concerning this was from @nickfox-taterli, telling they assigned some tests to a person (besides @yoyojacky) to proof the error.
> No public results, yet.
> 
> Good idea to let you be informed from the RPi.
> Go one step beyond and use one of the RPis GPIOs to interrupt the power supply automatically...
> Weird but constructive :)
> 
> Harry

Seems like my colleage have send you a test video of those UPS PLUS?

**Comment by yoyojacky** [comment]
My colleague said that he has negotiated with you to give you a refund. She should have sent you the result of our test

**Comment by deHarro** [comment]
> 
> 
> My colleague said that he has negotiated with you to give you a refund. She should have sent you the result of our test

HI @yoyojacky !
Yes, I am in touch with Cheney and got the refund weeks ago. That is all fine from my side.
And she promised me, that I get a new UPS (upgraded version or one with a new firmware) as soon as you found a solution for the reported errors.

Sadly, I cannot follow your statements, since I and others got the reported errors and proved them with evidence videos and pictures.
But I'm willing to give your UPS another chance.
I will get in touch with Cheney and ask for the new UPS, as promised.

Thanks so far!
Harry

**Comment by deHarro** [comment]
> 
> 
> Sorry for my slow response, and I have already tested two USP PLUS which sent back from Harry, and One of the pins of the UPS charging chip was unsoldered. After re-soldering, the firmware of V8 was upgraded. After running for a week, there was no power failure. Other one works properly .

"Harry" from the discussion with aftersales support (Cheney), that is me (@deHarro here at Github).

> Other one works properly .

You and Cheney stated, that you operated this one for 2 days without error.
I told you, that the error occurs at different timely distances, mostly it lasts more than 24 hours. So perhaps you didn't run the test long enough?

> and I used a charger which supports QC protocol, and charging voltage is 9.01V

This is, what I use, too. 
So there is hope, that a newly delivered UPS will function properly...

Harry (deHarro)

**Comment by deHarro** [comment]
@yoyojacky 
> Seems like my colleage have send you a test video of those UPS PLUS?

No test video, just some lines af text. But I trust your writings, even without a video ;)

Harry

**Comment by deHarro** [comment]
> 
> 
> I set up a telegram bot to warn me when batteries voltage starts dropping while connected to the charger and noticed it happens every 24 hours with quite a lot of certainty:
[picture snipped]
> When the bot messages me, I plug and unplug the power supply in order to keep the raspberry pi from powering down after a few hours.

Hi Leandro! @leandroalbero 
Can you please post the part of your script where you decide to launch the warning telegram?
Thanks!

Harry

**Comment by drtywheels** [comment]
Frustratingly I too suffer from the input charge stopping after 24hrs (almost on the dot). (current supplied from power supply drops to 0 regardless of type-c or microusb).
I don't run any of this repo's scripts on a schedule. I probably should so I get a graceful shutdown but I've never had the device run longer that 24hrs without killing the batteries and requiring the usb input to be unplugged and re-plugged. 

I'm now running a script to notify me via mqtt pub on failure so I can get to it before draining the batteries.

Pretty disappointed with the product so far.

**Comment by zanes83** [comment]
May I know if there is any further development for this issue?

Currently using UPLSPLUS EP 0136 firmware 10

Situation
- Battery depleted below 3.00Vdc,
- Plugin charger 5V 3A
- UPS output to rpi keeps turning On and Off
- Battery unable to charge up and rpi
- rpi keeps On and Off
- already burnt 2 pieces of my rpi (wasted money) due to this issue
- need to remove load (rpi) only able to charge up battery
- that's a turn around, not solution for long run 

Is there any other turn around other than removing load to charge it first? Or is that how an UPS should work?

Or is the UPS EP0136 can be programmed, so that it will focused on charging battery until Protection Level achieved only will turn on the load from Ups? 

Thank you

Zanes

**Comment by miamilabs** [comment]
> May I know if there is any further development for this issue?
> 
> Currently using UPLSPLUS EP 0136 firmware 10
> 
> Situation
> 
>     * Battery depleted below 3.00Vdc,
> 
>     * Plugin charger 5V 3A
> 
>     * UPS output to rpi keeps turning On and Off
> 
>     * Battery unable to charge up and rpi
> 
>     * rpi keeps On and Off
> 
>     * already burnt 2 pieces of my rpi (wasted money) due to this issue
> 
>     * need to remove load (rpi) only able to charge up battery
> 
>     * that's a turn around, not solution for long run
> 
> 
> Is there any other turn around other than removing load to charge it first? Or is that how an UPS should work?
> 
> Or is the UPS EP0136 can be programmed, so that it will focused on charging battery until Protection Level achieved only will turn on the load from Ups?
> 
> Thank you
> 
> Zanes

I face similar issue here.
Any way to fix it or i send all units back to Amazon. Have 15 of those units and pi keep turn on off and wont charge at all after power outage.

**Comment by NightFlowed** [comment]
Same problem here @yoyojacky 
![Screenshot_20250105-033614](https://github.com/user-attachments/assets/87eafc15-4fbf-4636-b9d0-f7286448f386)

Power adapter attached to the device (USB C power adapter from Ugreen)

I have created a stack to monitor all statistics on a grafana+Prometheus dashboard, so I see all value in real-time. I'm writing an app to send theses data to an home assistant via MQTT (not finished)

I clearly see that power supply is supplying 9.0V to the UPS (with some variation of some mV every sec that prove it's not bugged) But the UPS suddenly keep draining batteries until they die. 

I've tried to see if it was a "periodic phenomenon" but it seems to be random. One time after 2 hours, another time 24h after, and so on.

Batteries are good, they keep the Pi on for more than 4 hours.

It seems that when I doesn't do any I2C read or write, the UPS never have this issue. Not pretty sure but a least 2 week with no issue if there is no i2c. 

So I clearly think this i an internal firmware bug/issue.
Hardware is good, because my ups worked fine for many month until i start writing my app.

If there was a command to reboot the UPS software i could just restart if I saw more than 1A draw current on battery and more than 1V on USB supply at the same time... but there is no such command and no command to restart or shutdown the UPS while it has USB connected... 

Work around for the moment :
I send a command to an external "connected plug" to disconnect USB and then reconnect if I saw more than 1V on USB and more than 1A current draw on battery. Work fine with that.

So, if you could : 
 - find this bug and correct it.
 - add an i2c command to cut off the Pi supply and then repower it after a certain countdown for example.
 - add an i2c command to restart the internal software

Feel free to contact me if you need. 
(I'm an embedded electronics ingeneer hardware and software so I can check many things if you need)

PS : you will seen attached graph of the bug than appears at 22h30. I unplugged/replugged at 2h24.

**Comment by deHarro** [comment]
May I step in here again...
I am still waiting for an updated version of the UPS (since 2021). 
The only feedback I got after inquiry was, "the found solution is not satifying your demands" (more or less, they used another wording).
Nevertheless they still sell this version up til now, seemingly with the same problems/errors :(
I'm deeply disappointed.

Harry

**Comment by yoyojacky** [comment]
> Same problem here [@yoyojacky](https://github.com/yoyojacky) ![Screenshot_20250105-033614](https://github.com/user-attachments/assets/87eafc15-4fbf-4636-b9d0-f7286448f386)
> 
> Power adapter attached to the device (USB C power adapter from Ugreen)
> 
> I have created a stack to monitor all statistics on a grafana+Prometheus dashboard, so I see all value in real-time. I'm writing an app to send theses data to an home assistant via MQTT (not finished)
> 
> I clearly see that power supply is supplying 9.0V to the UPS (with some variation of some mV every sec that prove it's not bugged) But the UPS suddenly keep draining batteries until they die.
> 
> I've tried to see if it was a "periodic phenomenon" but it seems to be random. One time after 2 hours, another time 24h after, and so on.
> 
> Batteries are good, they keep the Pi on for more than 4 hours.
> 
> It seems that when I doesn't do any I2C read or write, the UPS never have this issue. Not pretty sure but a least 2 week with no issue if there is no i2c.
> 
> So I clearly think this i an internal firmware bug/issue. Hardware is good, because my ups worked fine for many month until i start writing my app.
> 
> If there was a command to reboot the UPS software i could just restart if I saw more than 1A draw current on battery and more than 1V on USB supply at the same time... but there is no such command and no command to restart or shutdown the UPS while it has USB connected...
> 
> Work around for the moment : I send a command to an external "connected plug" to disconnect USB and then reconnect if I saw more than 1V on USB and more than 1A current draw on battery. Work fine with that.
> 
> So, if you could :
> 
> * find this bug and correct it.
> * add an i2c command to cut off the Pi supply and then repower it after a certain countdown for example.
> * add an i2c command to restart the internal software
> 
> Feel free to contact me if you need. (I'm an embedded electronics ingeneer hardware and software so I can check many things if you need)
> 
> PS : you will seen attached graph of the bug than appears at 22h30. I unplugged/replugged at 2h24.

Did you replace the batteries before ? it seems like the batteries are not working properly...

**Comment by yoyojacky** [comment]
> May I step in here again... I am still waiting for an updated version of the UPS (since 2021). The only feedback I got after inquiry was, "the found solution is not satifying your demands" (more or less, they used another wording). Nevertheless they still sell this version up til now, seemingly with the same problems/errors :( I'm deeply disappointed.
> 
> Harry

Do you have the same problem? please contact our sales men by sending email to sales@52pi.com

**Comment by NightFlowed** [comment]
Hi @yoyojacky ,
Thanks for your answer.

Batteries? Really?
I've changed them many times because this issue make them drop in under voltage. 
These are quality batteries. If you see the curves, you will remarks that they hold power during 4 hours at 2.5 amps. Bad batteries cannot hold this. 
This is equivalent to 10amp/hours with two 18650, so batteries are okay.

If you pay attention to the curves, you will clearly see that the UPS stop charging beside 9V are present on USB. Could you explain that issue ?

Regards

**Comment by deHarro** [comment]
> > May I step in here again...
> > ...
> > Harry
> 
> Do you have the same problem? please contact our sales men by sending email to [sales@52pi.com](mailto:sales@52pi.com)

Hi @yoyojacky ,
no, I sent the two UPS I bought back then (in 2021) back to you following your wish.
At the moment I have no UPS in action.
But I can assure, back then I had the same problems as outlined by "MarcianoFlorian", but not traced as good as he. I tried to describe the problem verbally.

Regards, Harry

**Comment by deHarro** [comment]
> yoyojacki said:
> Do you have the same problem? please contact our sales men by sending email to [sales@52pi.com](mailto:sales@52pi.com)

I did so (again?) and got the answer, that I should replace the batteries... 😖
I thought, we are way beyond batteries.

Obviously the sales men do not read this Github issues listing, or they would have had realized, that the batteries are NOT the problem.
