### ISSUE TITLE
The current and power readings of the Raspberry INA219 are way too big

### ISSUE THREAD

**Issue by deHarro** [geeekpi/upsplus#37]
I am in a lengthy conversation with the hotline of GeeekPi concerning [UPS stops powering the system with charger still attached](https://github.com/geeekpi/upsplus/issues/36), despite the fact, that the charger still delivers power.

In the beginning the staff insisted on "bad/weak batteries" and a very heavy overall power consumtion of my system.
In the path of tracking down the problem I realized, that the readings of the INA219 are more than 5 times bigger than metered with a clamp-on ammeter.
By tweaking the SHUNT_OHMS parameter in the INA instantiation and setting some other parameters in the configure call to reaonable values I managed to make the readings more or less consistent to each other.

My initialisation of the INA chip **for the Raspberry** is now 
```
MAX_EXPECTED_AMPS = 2
SHUNT_OHMS = 0.007 * 5.5

# Instance INA219 and getting information from it.
ina = INA219(SHUNT_OHMS, MAX_EXPECTED_AMPS, address=0x40)
ina.configure(ina.RANGE_16V, ina.GAIN_2_80MV, ina.ADC_32SAMP,  ina.ADC_32SAMP)
```

Harry

**Comment by deHarro** [comment]
They are informed already. Thanks!

Concerning the accuracy:
I cannot meter such low resistances, my equipment is limited.
But by fiddling around with the parameters, I found, that I have to adjust the SHUNT_OHMS parameter to more than 5 times bigger than set in your scripts.
This resulted in 5 times too big readings from your scripts.

I described my test setup already to the after-sales staff.
I soldered a wire to a double sided PCB so I am able to attach a clamp-on ammeter. This PCB I put between the pogo style pins of the UPS and the RPi and so I am able to get the real current to the RPi.

I went this path since the staff always told me that my batteries are bad/weak and the RPi is drawing way too much current at all.
Now I know, my batteries are ok and the system power usage is well within the expected bounds.

Harry

**Comment by ArjenR49** [comment]
I measure about 0,7 A @ 9,25 V input to the UPS from the charger and at the same time the current to the RPi is given as 2,2 A @ 5V by the UPS. I have an SSD in a UGreen enclosure and don't know how much that takes, but it all comes from the UPS through the pogo pins. Then there's the batteries which are charging at less than 200 mA according to the UPS. And the Ice Tower fan with the fancy lights. Plus a standard camera, no lights.

I'd say in my case the current the UPS reports is roughly 50% too high. Roughly ... there's losses in the voltage convertors, which makes it only worse. 0,7 A at 9,25 V is only 1,3 A @ 5 V, without taking losses into account.
My batteries are keeping their charge, thank you ;-) at 4,2 V or so.
So the 1,3 A or so is all there can be available on average.

I didn't look at it this way before, and just thought, oh the Pi4, it is so very power hungry, but Harry obviously has a point.
I measured charger output voltage and current with the handy little and ubiquitous USB module made by Rui Deng.

**Comment by deHarro** [comment]
My first glimpse when seeing my trace files was "Upps, why are the power values of RPI and batteries so far apart??".

If the PRI is powered only by batteries (no charger attached), then the power readings in the battery path and the PRi path should be similar, perhaps differ in some percent for the losses in the various converters.

In my case I had something like that:
Vbat 4,164 V, Ibat -1973,9 mA, **Pbat  7673,2 mW** - Vrpi 4,980 V, Irpi  3085,5 mA, **Prpi 15282,2 mW**

That is double the power of the battery to the RPi, physically impossible.

So I started to study the datasheets of all components on the UPS as well as the INA219 library used by Python.

Matching the readings of my clamp-on ammeter with the readings from INA219 and fiddling with the parmaters for the INA219 initialisation I managed to get those readings close together.

My findings are seen [here](https://github.com/geeekpi/upsplus/issues/37#issue-896716560).

This is naturally true only for my given device.
@nickfox-taterli told me, that they meter not only the shunt resistor with the INA chip, but also the MOSFET.
Both have deviations from their norm values and so another UPS may have other parameters.

Harry

Harry

**Comment by ArjenR49** [comment]
Hi,
I did read your posts before adding my post.
I don't know the ina device, but I gather the first parameter is the shunt
resistance across which the ina measures, 0,00725 something.

How come you arrived at a 5 times bigger value? It would mean your current
value as given by the ina would go down to 20% of what it was, wouldn't it?

Thanks!
Arjen
(On The Road)

Op vr 21 mei 2021 10:53 schreef deHarro ***@***.***>:

**Comment by deHarro** [comment]
> How come you arrived at a 5 times bigger value? It would mean your current value as given by the ina would go down to 20% of what it was, wouldn't it?

I described the procedure [here](https://github.com/geeekpi/upsplus/issues/37#issuecomment-845056201).

I bent the PCB two times to avoid penetrating too far between the pogo contacts and inserted it into the power path from UPS to RPi. This way I can meter the current without big deviations induced by long wires or additional resistances in the path.

Additionally to these measures I traced the voltage over the shunt resistor the INA chip tells me, the library has a call for that. I got a reading of ~20 mV, compared against the value across the resistor metered with my DMM, ~4 mV.
This also derives a factor of ~5 times.

**Comment by ArjenR49** [comment]
I also asked because your INA-configuration statement is very different from what GeeekPi uses:
ina.configure()
which looks like a default configuration ...

You use:
MAX_EXPECTED_AMPS = 2
SHUNT_OHMS = 0.007 * 5.5

# Instance INA219 and getting information from it.
ina = INA219(SHUNT_OHMS, MAX_EXPECTED_AMPS, address=0x40)
ina.configure(ina.RANGE_16V, ina.GAIN_2_80MV, ina.ADC_32SAMP,  ina.ADC_32SAMP)

Why did you need to add all those parameters on ina.configure?

**Comment by ArjenR49** [comment]
After the UPS shut off the Pi because the batteries were below 3,5 V, I reconnected the charger.
It now supplies 1,8 A at about 9 V which is what it can do according to the info on the device.
However the UPS tells me the batteries are charging with more than 5 A. That is at the batteries voltage level so the current will be higher for the power provided by the charger, but from 1,8A at 9V to 5,3 A at 3,7V is 22% too much even without conversion losses.

I added rounding to all values from the start of my work with this UPS because I didn't believe showing, mV and mA accuracy, but I didn't expect more than 20% off.
That said, it's probably not important for the operation of the UPS as long as the voltages measured are correct.
10% accuracy on the currents would be acceptable, I'd say.

**Comment by deHarro** [comment]
> Why did you need to add all those parameters on ina.configure?

As written, I fiddled around with the parameters a bit... ;)

The default parameters are used by GeeekPi, yes.

Adjusting only the factor for the shunt didn't accomplish sufficient results, so I tried oversampling and filtering.
The range for the voltage is 32 V max by default. When cut down to 16 V, the resolution is better (as the datasheet states).
Same with the to be expected maximum voltage readings over the shunt.
This in deed did the job, the readings of the DMM and the INA chip are very similar (at least to a certain extent. The average current fits, but the process of reading the vlaues over I2C pushes the current on the RPi momentarily. I have no clue about the timing correlation between the different meters).

Harry

**Comment by yoyojacky** [comment]
hi Harry, Is it because of the INA219 reading problem that caused you to shut down? Or is it due to insufficient voltage supplied by the UPS to the Raspberry Pi?

**Comment by nickfox-taterli** [comment]
The actual Raspberry Pi side of the current sampling consists of sampling resistors and PMOS, PMOS model NCE20P85G, they both have a certain error, for more than 0.5%, in our tests, we use a series ammeter test, the final result of a more appropriate value, and if you use our value test out the results are significantly larger, it is best to check the code or you think need to get higher accuracy, you need to measure the actual sampling current or actual sampling resistance yourself.

Our actual test, if the Raspberry Pi brand new system, not connected to other peripherals, the test yielded a Raspberry Pi current consumption of roughly 1.4A. According to the picture you provided, you connected the peripherals, peripherals consumed 500mA, connected between the Raspberry Pi power supply circuit wires, wires generated a voltage drop, its battery discharge and the upper limit of discharge limit, whether it has reached the limit of battery discharge, which is also a parameter to be considered, our actual test, has been able to supply power for many days without power failure, we connected a cooling fan and some other Peripherals, the total consumption of about 2A.

In our tests, if the battery charging and discharging parameters are not good, and the power is too high, the final battery will certainly not be charged, and finally not only can not charge the battery, but also need to absorb the battery current, each battery discharge capacity and charging capacity and capacity have an upper limit, and, not blindly believe the capacity of the battery label, which is usually very easy to fake.

We have used poor quality batteries and conventional loads, as well as normal batteries and conventional loads for testing, testing specific results can be @yoyojacky 

If you think it is a product quality problem or can not be solved, we suggest you apply for after-sales service.

**Comment by deHarro** [comment]
>hi Harry, Is it because of the INA219 reading problem that caused you to shut down? Or is it due to insufficient voltage supplied by the UPS to the Raspberry Pi?

hi @yoyojacky, 
First we have to agree on what "shutting down" you refer to.
If you refer to shutting down the RPi because of too low voltage on the batteries:
-> My test script (I use to generate the trace files I provided you with) permanantly checks the INA219 output of the battery voltage. "Permanently" is every 3 seconds.
If the voltage falls below a given value, it issues the shut down sequence to the RPi.

If you refer to the shut down of the charger supply (UPS stopps to use the current from the charger to supply the system consisting of UPS and RPi + SSD):
-> The charger I use is a genuine Raspberry Pi 4 supply device. It delivers 5.1 V @ 3 A. This is definitely sufficient for both, driving the RPi + SSD and concurrently charging the batteries, if they are depleted to ~3.6 V. This is the "running state".
During "running state": In my traces I see, that after several time the battery charging current drops to below 50 mA and begins to toggle between charging and discharging with this low current. This I interprete as "battery is fully charged". In this situation the current drawn by the RPi + SSD sustains at around 500 mA.
-->> And despite this described and considered as "normal" situation, suddenly the UPS stops to deliver current to the RPi.

So, now we talk about the same "shut down", what exactly is, what you ask for?

Additional information: I never realized any access errors when reading the INA219 chips. 

Thanks!
Harry

**Comment by deHarro** [comment]
Hi @nickfox-taterli,
my concerns with the accuracy of the INA219 readings are more or less founded by the answers of the after-sales staff. 
In the beginning of my chat with them, they permanently claimed "bad batteries, not feasible to deliver such high currents and power" and referred to the readings of the INA chips.
It was a hard time to convince them from the quality of my batteries, but now, after I demonstrated the readout errors, based on "inaccurate" initialization parameters, they come around.

> ... a Raspberry Pi current consumption of roughly 1.4A. 

I suppose you are testing with a RPi 4. This variant is known to draw relytively high currents.
My RPI is of type 3B+ and both systems I test with draw around 500 mA in normal operation. The SSD I run my system from draws another 100 mA sustained, so I have roughly 600 mA system current.

> In our tests, if the battery charging and discharging parameters are not good, and the power is too high, the final battery will certainly not be charged, and finally not only can not charge the battery, but also need to absorb the battery current, each battery discharge capacity and charging capacity and capacity have an upper limit, and, not blindly believe the capacity of the battery label, which is usually very easy to fake.

I certainly believe - and delivered evidence many times by trace files - that my batteries are capable of storing around 3 Ah (each of the two paralleled batteries storing 1.5 Ah). That is less than printed on the labels, I agree with you, but 3 Ah are enough to drive my system for around 4 hours without charger (also proofed with trace files).

My actual theory directs to concurrency problems in the firmware.
I yesterday started a test without runing my trace script. So only the crontab fires your "upsPLus.py" and "upsPlus_iot.py" every minute.
My thoughts are, perhaps my relatively frequent calls to the INA219 and the I2C registers of the µC lead to deadlocks in the firmware, when they interfere with the concurrently running calls from the crontab jobs, aiming at the same hardware ressources.
Just my 2 cent...

You may test this theory by reading the INA chips and the µC registers heavily in concurrent threads. 
I too, will start such tests soon. 
My expectation is, the problematic situation (UPS stops charger current from supplying the system) should occur more often or in shorter intervals when sampling the INA chips and registers, lets say, once every second from two or more threads.

> If you think it is a product quality problem or can not be solved, we suggest you apply for after-sales service.

Concerning the dead second UPS I'm already in contact with them. Thanks!

Harry

**Comment by deHarro** [comment]
@nickfox-taterli 
> I yesterday started a test without running my trace script. So only the crontab fires your "upsPLus.py" and "upsPlus_iot.py" every minute.

This is not aiming the problem, as the UPS yesterday in the evenning stopped powering the system, even without running my additional scripts :(

Next I will start testing with no script running at all. 
If this results in the same error condition, then it doesn't depend on the register accesses.
I will keep you posted...

Harry

**Comment by deHarro** [comment]
@nickfox-taterli
Ok, no more tests from me, I just shipped the two devices to GeeekPi. I hope you find the error...

Harry

**Comment by nickfox-taterli** [comment]
The test task has been assigned to @yoyojacky .

**Comment by deHarro** [comment]
Hi @yoyojacky,

I'm informed by the post office, tha tmy two UPS arrived at your site.
Did you already have a chance to start testing? 
Did the error condition occur?

If you need additional input, just ask, I am eager to help with hints.
Thanks!

Harry
