### ISSUE TITLE
charging issue

### ISSUE THREAD

**Issue by Zbrooklyn** [geeekpi/upsplus#41]
when I plug in the charger the raspberry pi turns on automatically how come?

I feel it should only turn on when I push the power button how do I fix that

**Comment by ArjenR49** [comment]
Your ups may have register 0x19 set to 1, which means power up the Pi when AC is connected.
You can run e,g. either of my UPS_report*.py scripts to see the contents of that register at any one moment in time. You can find those scripts here: https://github.com/ArjenR49/UPS-Plus
