### ISSUE TITLE
[Feature Request] UPS without battery installation

### ISSUE THREAD

**Issue by greatss** [geeekpi/upsplus#45]
I have purchased other UPS products, such as BK325I, which does not require the installation of batteries, but he is relatively bulky, I only use it to power the Raspberry Pi, so I need a lightweight, but this product requires batteries, I tried without batteries, simply can not start.

**Comment by nickfox-taterli** [comment]
If there is no battery how to provide electricity?

**Comment by yoyojacky** [comment]
Do you use love to generate electricity without batteries?
