### ISSUE TITLE
Unable to set the protection voltage

### ISSUE THREAD

**Issue by Rubber1Duck** [geeekpi/upsplus#78]
hi all,
when i set the protection voltage to 2500 mV and after that control by reading the register all seems fine , but a few seconds later the value is reset to 3700 mV when rereading the register!

What i am doing wrong? (FW is 10)

**Comment by ArjenR49** [comment]
2500 mV is too low a value. It's probably the f/w which resets it to the
default 3700 mV.

The lowest safe value for some batteries according to their specification
sheet may be 2700 mV, but the ups f/w may not allow it.


Arjen
(On The Road)

Op vr 17 sep. 2021 14:09 schreef Peter ***@***.***>:

**Comment by Rubber1Duck** [comment]
Thanks @ArjenR49  ............. 2800 mV seems to work ...............
I could have figured it out myself ................... :-)
