### ISSUE TITLE
Hardware Version 5.0 to 5.3. Changes related to INA219?

### ISSUE THREAD

**Issue by ve7wrs** [geeekpi/upsplus#97]
My first UPSPlus was HW Rev 5.0. I upgraded the firmware to Rev 10. I recently purchased a second UPSPlus which is HW Rev 5.3. It arrived preloaded with Rev 10.

I'm getting different results from the current sensing INA219. Before I investigate further - is there a HW change related to the INA219 circuit?

**Comment by yoyojacky** [comment]
No, it is just some pcb producing tag, it is the same.
